name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm build

    - name: Deploy to Netlify
      run: netlify deploy --site "${{secrets.NETLIFY_APP_ID}}" --auth "${{secrets.NETLIFY_TOKEN}}" --dir "dist" --prod